version: "3.9"
services:
  api:
    build: .
    container_name: veneto_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: veneto_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: